version: '3'

networks:
  api-bridge:
    driver: bridge

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rest-rabbit
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - api-bridge

  mongodb:
    image: mongo:4
    container_name: api-database
    ports:
      - 27017-27019:27017-27019
    volumes:
      - /tmp/Docker/mongodb:/data/db
    networks:
      - api-bridge

  rest:
    build:
      context: .
    container_name: rest_api
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - mongodb
    networks:
      - api-bridge
    entrypoint: ./waitForRabbit.sh

  analytics:
    image: registry.hub.docker.com/rainowy/people_analytics
    ports:
      - 8081:8081
    restart: on-failure
    depends_on:
      - rabbitmq
      - rest
    networks:
      - api-bridge

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
    networks:
      - api-bridge


