version: '3'

networks:
  api-bridge:
    driver: bridge

services:
  #  api-database:
  #    image: mongo:3.2.4
  #    container_name: "api-database"
  #    ports:
  #      - 27017:27017
  #    command: --smallfiles
  #    networks:
  #      - api-net
  mongodb:
    image: mongo:4
    container_name: api-database
    ports:
      - 27017-27019:27017-27019
    volumes:
      - /tmp/Docker/mongodb:/data/db
    networks:
      - api-bridge


  demo:
    build:
      context: .
    container_name: demo
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - mongodb
    networks:
      - api-bridge
    entrypoint: ./entrypoint.sh
  #    environment:
  #      - ENV=loc
  #    command: tail -f /dev/null



  #     links:
  #       - api-database



  #added by Tomek
#  mongo-seed:
#    build: ./mongo-seed
#    #    links:
#    #      - api-database
#    networks:
#      - api-bridge


