version: '3'

networks:
  api-bridge:
    driver: bridge

services:

  mongodb:
    image: mongo:4
    container_name: api-database
    ports:
      - 27017-27019:27017-27019
    volumes:
      - /tmp/Docker/mongodb:/data/db
    networks:
      - api-bridge

  rest:
    build:
      context: .
    container_name: rest_api
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - mongodb
      - mongo-seed
    networks:
      - api-bridge
    entrypoint: ./entrypoint.sh

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
    networks:
      - api-bridge


