version: '3'

networks:
  api-bridge:
    driver: bridge

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: people_rabbit
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - api-bridge

  mongodb:
    image: mongo:4
    container_name: people_database
    ports:
      - 27017-27019:27017-27019
    volumes:
      - /tmp/Docker/mongodb:/data/db
    networks:
      - api-bridge

  rest:
    image: registry.hub.docker.com/rainowy/people2
    container_name: people_rest
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongodb
      - mongo-seed
    networks:
      - api-bridge

  analytics:
    image: registry.hub.docker.com/rainowy/people-analytics2
    container_name: people_analytics
    ports:
      - 8081:8081
    restart: on-failure
    depends_on:
      - rabbitmq
      - rest
    networks:
      - api-bridge

  mongo-seed:
    image: registry.hub.docker.com/rainowy/people_mongoseed
    container_name: people-mongoseed
    depends_on:
      - mongodb
    networks:
      - api-bridge


