micronaut:
  application:
    name: rest
  server:
    port: 8080
mongodb:
  uri: mongodb://localhost:27017/humans
#  auto-index-creation: false
#mongodb:
#  host: mongodb
endpoints:
  health:
    enabled: true
rabbitmq:
  uri: amqp://localhost:5672